name: recipe_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.1


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  
  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Bold.ttf
          weight: 700
        - asset: fonts/Lexend-Light.ttf
          weight: 300
        - asset: fonts/Lexend-Medium.ttf
          weight: 500
        - asset: fonts/Lexend-Regular.ttf
          weight: 400
        - asset: fonts/Lexend-SemiBold.ttf
          weight: 600
 